---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: default
    - name: node-feature-discovery
      namespace: kube-system
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.8@sha256:e37b9355b648a4253131961b94bf6f98f79975fcac1fbd8fb515ff87d4422ab1
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8096
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      data:
        enabled: true
        type: nfs
        server: "${CONFIG_NFS_SERVER_ADDRESS}"
        path: "${MEDIA_NFS_SERVER_PATH}"
        mountPath: /data
      transcode:
        enabled: true
        type: emptyDir
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 6000Mi
