---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media-files
  labels:
    app.kubernetes.io/name: recipes
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static-files
  labels:
    app.kubernetes.io/name: recipes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
