apiVersion: v1
kind: Secret
metadata:
    name: recipes-secrets
    labels:
        app.kubernetes.io/name: recipes
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:wfjPdpt+1EkCbiPFD3gJzYTUGpfeCaJ3ddYT4ubFr/qlrQWu,iv:a18iMO2Q62DTz3wtWqzisBoz/DYwPFNnLScRJIkEw/A=,tag:4orVpj0YS5i61IOoIYNl4Q==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:s+hhsSrSUclNNDKOLyA=,iv:egDd9SS1ZaAUeVKlgAmnJJiNRGS83w43OKOra20/m8M=,tag:nB+eRClfCu0ZZuo8MfAA1Q==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:mPeg7w==,iv:ywRdBLdFadlYTIHbA0cYVjYkPCiE5HrC0hT4YRmVgnU=,tag:KvKiO223JAU+hy9aza1AvA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:RXv3EaO+Hw==,iv:s1iYYDpei0xrNXLiiER8O1UEthVJFwsNEYtQJ7S4v0c=,tag:LIdFbN9vuYdDM80MLKmUZA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:syrujECYu9ZKK1Wpa3x9bdiN38k=,iv:qYGvI4bGobUtK21K8MwMmRiOIwSrpedM1UWsVPu5lEQ=,tag:lYzyJiNrlFCA8TrKAQ1Nag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWdMMzdpc3ByeHNiWVBx
            VmE5ZUNGTi9oeWNCaHMxS1c3ODJaVXU2d2s4CnNQSW5hYUQ4eVFuNnE1TWxOUEhq
            OE5xUnUva213Tm1LZ1I2LzZOZVZrZGsKLS0tIFNPam5vRExmZXE5RFNzQ3pYMTI4
            YjVjUGRibjArVW85QkcvMW9seWprVEEK5FXBGlZ3fl/TJJPnICmcN244s18dyEH4
            G2zxXkzk73295WAlKpqmPVDOTiRnjFZI3+jo3MgUz8MkUkqhyU2zEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T09:41:41Z"
    mac: ENC[AES256_GCM,data:UNscCjjiKd+03Cl5v0nERAosaHseKNWdTzYt9EMHFfsgrXxNtfC+U4Ictw0xGu9MhrcwpMeCQpTmzfE7MZLg2Xku3lTtn03GioHhhjt1c3nR2MlMsv5BSK/t3L29Bs9AtUS9roEaoCxRGgOSshE785WvtYnAI3hLX1u0IhC2GL8=,iv:hBhcAVg222fAUWF0Y+nSBBIX9HlPTiJQT+sw+SBWGdA=,tag:uhI8gWwLwUdFtshYdOqWYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
