---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: dns-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      dnsPolicy: ClusterFirst
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.10.2
          args:
            - --source=ingress
            - --source=service
            - --provider=coredns
            - --log-level=debug # debug only
            - --domain-filter=${SECRET_DOMAIN}
          env:
            - name: ETCD_URLS
              value: http://etcd.dns-system.svc.cluster.local:2379
