---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  labels:
    helm.sh/chart: adguard-home-5.2.0
    app.kubernetes.io/name: adguard-home
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: release-name
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  labels:
    helm.sh/chart: adguard-home-5.2.0
    app.kubernetes.io/name: adguard-home
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: release-name
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  labels:
    helm.sh/chart: adguard-home-5.2.0
    app.kubernetes.io/name: adguard-home
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: adguard-home
