---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tatort-bot
  labels:
    app.kubernetes.io/name: tatort-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tatort-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tatort-bot
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
        - name: tatort-bot
          image: "ghcr.io/clempat/tatort-telegram-bot:main"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: tatort-bot-secrets
