apiVersion: v1
kind: Secret
metadata:
    name: tatort-bot-secrets
    labels:
        app.kubernetes.io/name: tatort-bot
type: Opaque
stringData:
    CHAT_ID: ENC[AES256_GCM,data:sUITY2TQw0jw+/aZb3Y=,iv:NXrWicNMpZCA7nCzmrFL8EW16WjvkstZR2Nbc4Pzny4=,tag:YMAnPxTaA0Mm6IrPrnM8zw==,type:str]
    BOT_TOKEN: ENC[AES256_GCM,data:t7beaI9ThYvcRmeYoWHXj7nTFkvUKxpxQrT5Ez4IeD5Y6VNMkFCRf9ANWN56,iv:AKheGSHI2zWLWsIx6YylE2uUudRo0j1g9zRdWpMRC1E=,tag:E9yiNaOYGcMfVhAcYEU5UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMERQbWJiNmRPdllndFgv
            TUhzUlJoQlFMa2lUM2J3bUFmWk1kWFZSdVVVCjhYL1FtZm9PMnFXZ3QvSitZcklX
            OEk3bEJwZEp3L3Z2UTgwZ1JoOUVBMTgKLS0tIDVWUmxKWndDYVFoSDByOG9TTGVp
            cWtxSmJ2Mm9ya0hpWjFPUWd6ZEdvMkkKSLi9rh588B51kbEuXtrWONZhcdSLb54i
            mR6tOBYY1A7LH3JE09dzYdOrFk3H8CtoZbeVdhXw4ZSUe20olcPjow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T08:42:10Z"
    mac: ENC[AES256_GCM,data:KDhNMo+Rkohh9vQsa1N+ALnERBsk64bijLjxf6FIrv9eZBxb48NiZiMrAXBZHq8xNuXoyEKqGbiE+jPGtyyE1WhcacI21+Uv7ksQYpv/FhJONg1jLoSLGQ2jXJWGms8qczORSJLHeAqGRnzI4yauuV/nPmjxx66EjAzbdbwM8Q0=,iv:tYwplcwV2CccKmNiKdDVnBYh8jX/fZkaOR63H+EyvCg=,tag:wvVQmL9brI6jgsLzbRBIHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
