---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configs
  namespace: authentication-system
  labels:
    app.kubernetes.io/name: authelia
data:
  configuration.yaml: |
    theme: auto
    default_redirection_url: https://auth.${SECRET_DOMAIN}
    server:
      host: 0.0.0.0
      port: 9091
      read_buffer_size: 4096
      write_buffer_size: 4096
      path: ""
    log:
      level: debug
    totp:
      issuer: "${SECRET_DOMAIN}"
      period: 30
      skew: 1
    duo_api:
      hostname: ${SECRET_DUO_API_HOSTNAME}
      integration_key: ${SECRET_DUO_INTEGRATION_KEY}
    ntp:
      address: time.cloudflare.com:123
      version: 4
      max_desync: 3s
      disable_startup_check: false
      disable_failure: false
    authentication_backend:
      disable_reset_password: true
      refresh_interval: 5m
      file:
        path: /config/users.yaml
        password:
          algorithm: argon2id
          iterations: 1
          key_length: 32
          salt_length: 16
          memory: 1024
          parallelism: 8
    access_control:
      default_policy: deny
      rules:
        - domain: "*.${SECRET_DOMAIN}"
          policy: two_factor
    session:
      name: authelia_session
      expiration: 1h
      inactivity: 15m
      remember_me_duration: 1M
      domain: ${SECRET_DOMAIN}
      redis:
        host: redis.default.svc.cluster.local
        port: 6379
    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m
    storage:
      encryption_key: ${SECRET_AUTHELIA_ENC_KEY}
    notifier:
      disable_startup_check: false
      smtp:
        host: smtp.fastmail.com
        port: 465
        username: ${SECRET_AUTHELIA_EMAIL_0}
        sender: "Authelia Admin <admin@${SECRET_DOMAIN}>"

  users.yaml: |
    users:
      clement:
        displayname: "Clément Patout"
        password: "${SECRET_AUTHELIA_PASSWORD_0}"
        email: ${SECRET_AUTHELIA_EMAIL_0}
        groups:
          - admins
          - dev
