apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authentication-system
    labels:
        app.kubernetes.io/name: authelia
type: Opaque
stringData:
    authelia_jwt_secret: ENC[AES256_GCM,data:xV6Lg/b1M5+aNBvXhv7FSeSiemU=,iv:OsHSmy3EdDLw1ttyUbQE2ayylRwK0GXi66KZqhVsKG0=,tag:LxV+Mh10Yj5k5L2AkFourg==,type:str]
    authelia_duo_api_secret_key: ENC[AES256_GCM,data:HkAiZrM921RvmmH8S+We1AtZprkmurXa1Zxbzw9v5jVfc+AeWQrg5WWaBpeKXQpTTdZqrP9Rmuc=,iv:rJtVsBYTExCedDLtkk2hrGILj06eN4igcZ+WTbx9XdI=,tag:RIKwkJiktnQBRLdcH7BnnA==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:xcdJ7N74EcO5hrwDk+aoBj35yWs=,iv:Veu6sBTrXgn7U18wQ9rNjWh4QQK5PqVbMQ54LArR52Y=,tag:K/bcZIjdF6yY0iovucSGXQ==,type:str]
    authelia_notifier_smtp_password: ENC[AES256_GCM,data:J5DyZRSpIzj5c3SRD2inT3egEZmBM6IQ,iv:k6lGJVkvJCQJDjYWo1xrT5WaQy015ZtQ6FeuvHsVU38=,tag:4r/MnAynisvJAGQBTdexUg==,type:str]
    authelia_session_redis_password: ENC[AES256_GCM,data:OZhpg1dvmL/IN1REnYY=,iv:7MVoOA+eP1nMRNSDsG96RROQiwHky6WCv223HUsrpfE=,tag:TIVfSxId7f5kHvFgO5T9bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T20:09:49Z"
    mac: ENC[AES256_GCM,data:Q27035RdsBXL77lzQGhZL9ezHH9pgO/9qGvvnwx0QydXHwyWusi7lhlmnH203XpT1u+ASuG2YLQ8us5eR7hXaLY1meoSfFy9WGoWwWdAe8882lB2yahxz3hARJb0QnQeDYekTy9nQJSfra6RJ/h28xNirGmrxFc8hvf9mpXL+h4=,iv:gLXg29sIfq/gwRXT1Ko0iubIOHJyhY118TrFNy30F6E=,tag:SvPzqjrk3kTibkE8rKFrHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgo-cluster-pguser-authelia
    namespace: authentication-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflects: default/pgo-cluster-pguser-authelia
data: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T20:09:49Z"
    mac: ENC[AES256_GCM,data:Q27035RdsBXL77lzQGhZL9ezHH9pgO/9qGvvnwx0QydXHwyWusi7lhlmnH203XpT1u+ASuG2YLQ8us5eR7hXaLY1meoSfFy9WGoWwWdAe8882lB2yahxz3hARJb0QnQeDYekTy9nQJSfra6RJ/h28xNirGmrxFc8hvf9mpXL+h4=,iv:gLXg29sIfq/gwRXT1Ko0iubIOHJyhY118TrFNy30F6E=,tag:SvPzqjrk3kTibkE8rKFrHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
