apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authentication-system
    labels:
        app.kubernetes.io/name: authelia
type: Opaque
stringData:
    authelia_jwt_secret: ENC[AES256_GCM,data:xV6Lg/b1M5+aNBvXhv7FSeSiemU=,iv:OsHSmy3EdDLw1ttyUbQE2ayylRwK0GXi66KZqhVsKG0=,tag:LxV+Mh10Yj5k5L2AkFourg==,type:str]
    authelia_duo_api_secret_key: ENC[AES256_GCM,data:HkAiZrM921RvmmH8S+We1AtZprkmurXa1Zxbzw9v5jVfc+AeWQrg5WWaBpeKXQpTTdZqrP9Rmuc=,iv:rJtVsBYTExCedDLtkk2hrGILj06eN4igcZ+WTbx9XdI=,tag:RIKwkJiktnQBRLdcH7BnnA==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:xcdJ7N74EcO5hrwDk+aoBj35yWs=,iv:Veu6sBTrXgn7U18wQ9rNjWh4QQK5PqVbMQ54LArR52Y=,tag:K/bcZIjdF6yY0iovucSGXQ==,type:str]
    authelia_notifier_smtp_password: ENC[AES256_GCM,data:rHj4eUN11fZOtzavZbo+Zg==,iv:lP4KwUnN5/gY6rAHUeI0bKBRVkjBzsjR/eOwPHmfCCg=,tag:I7wHQi/s9VxRc3pF0J7ejg==,type:str]
    authelia_session_redis_password: ENC[AES256_GCM,data:aCBcTRupxPaLEXHWrmU=,iv:iZNKUbQzlhJ/xxppEWIxcVoQCDvW7RKETAFvDQBnLrM=,tag:Mk+9gGtGVFgXyb/L8yrJFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T21:32:38Z"
    mac: ENC[AES256_GCM,data:KT8SJ78IcguO+Mgi7hvq8h4SWRLf6W4N78+8GBHra+CbJpV2/An1uLzCBa3/nqNmAqRuUrP8WlqBy7TqqR/HhAnWRkO6qEMA+2Kw9r2kdHp663gxrki8y8fxjPNljaZa+aDoYZtnsdbtPnmdXgJEe294Gk6ufzYBqLuUMDsE5ho=,iv:5KCRjHy6pez0N+FoZ/uGQygGBIbwdSqDgFgVLa+d1Lo=,tag:X9Si3BtoxigrVEPWUVKvAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgo-cluster-pguser-authelia
    namespace: authentication-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflects: default/pgo-cluster-pguser-authelia
data: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T21:32:38Z"
    mac: ENC[AES256_GCM,data:KT8SJ78IcguO+Mgi7hvq8h4SWRLf6W4N78+8GBHra+CbJpV2/An1uLzCBa3/nqNmAqRuUrP8WlqBy7TqqR/HhAnWRkO6qEMA+2Kw9r2kdHp663gxrki8y8fxjPNljaZa+aDoYZtnsdbtPnmdXgJEe294Gk6ufzYBqLuUMDsE5ho=,iv:5KCRjHy6pez0N+FoZ/uGQygGBIbwdSqDgFgVLa+d1Lo=,tag:X9Si3BtoxigrVEPWUVKvAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
