---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authentication-system
    labels:
        app.kubernetes.io/name: authelia
type: Opaque
stringData:
    authelia_jwt_secret: ENC[AES256_GCM,data:PLS+HTHG8MdqywlQwjo=,iv:sBELVSQfLu/OHutJQcppiDIfrMCS5G7eZkSJOChL2Dk=,tag:rMREDstN7WFet1Szmn8j0w==,type:str]
    authelia_duo_api_secret_key: ENC[AES256_GCM,data:zFV15qlBmdUkMXLxJDNyiSsaSVr2JdDVdgaw+lLkl5HGx3qu8cSTyQ==,iv:Q+R0fG6UOaLBFFx3A85BxNMir8Fsu6sGIQVLHmqcanA=,tag:i+tKIROe4gWs0LXyruEPfA==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:aiwly7aGjrPEMZJ7Na8=,iv:dpSWQ5MO8iMddqnrGBJMlIhJzYcosGttqfJ9IJSdewM=,tag:BnmtY9Z9d542t2mmhxDO5A==,type:str]
    authelia_notifier_smtp_password: ENC[AES256_GCM,data:r9L8Q8dndoZ+Me/V+HQaMQ==,iv:JNXhnbEuPam5fSgtH6OrxVX/r9nsUbeq7UUXUIdCJzM=,tag:l1mlfA1Fj4OexEgRdk/uOg==,type:str]
    authelia_session_redis_password: ENC[AES256_GCM,data:h3GZiCbFaCUYaQXANAY=,iv:EMuy3pPCA7wZLYviZtgi6EVveIbKkjxPbZFOtUtbX5E=,tag:ffOkdpueHslzW6mdZBGUpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T07:39:20Z"
    mac: ENC[AES256_GCM,data:TRO+02FIGbIsbxD/GbIOLrxkr6zp/SbmOm5UkiJamAcfc3zhnZ+B3QPAKcpjQCdiTDhE/G5orbg2+5Akesla20DIlFnKwD49UeWUVGAI0r3CZlWlnyR8Soui5xd73mXanKBEwa/SdWAGfKfT/K6YEZkfAlOvsNzTncZOGk1e1z0=,iv:6xfMQgdzpltqFoDz1XndRIniR7wdiEnqULvYJFzb5Kc=,tag:h7eFk7COX0A0WMF/t5kgvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgo-cluster-pguser-authelia
    namespace: authentication-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflects: default/pgo-cluster-pguser-authelia
data: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T07:39:20Z"
    mac: ENC[AES256_GCM,data:TRO+02FIGbIsbxD/GbIOLrxkr6zp/SbmOm5UkiJamAcfc3zhnZ+B3QPAKcpjQCdiTDhE/G5orbg2+5Akesla20DIlFnKwD49UeWUVGAI0r3CZlWlnyR8Soui5xd73mXanKBEwa/SdWAGfKfT/K6YEZkfAlOvsNzTncZOGk1e1z0=,iv:6xfMQgdzpltqFoDz1XndRIniR7wdiEnqULvYJFzb5Kc=,tag:h7eFk7COX0A0WMF/t5kgvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
