---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.11.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      tolerations:
        - key: "hardware"
          operator: "Equal"
          value: "rpi"
          effect: "NoExecute"
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: zwave
              labels:
                zwave: "true"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class: {op: In, value: ["02"]}
                    vendor: {op: In, value: ["0658"]}
                    device: {op: In, value: ["0200"]}
            - name: intel-gpu
              labels:
                gpu: "true"
              matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: zigbee
              labels:
                zigbee: "true"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class: ["02"]
                    vendor: ["1cf1"]
                    device: ["0030"]
