# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4dlnFrnp1J1ooV9LSRCvznWQMx3OY4+6,iv:OIufc838iUBW4T/01Cz7sOlhInsi5me07Bnmq9rAsGI=,tag:LJEH90T3o3Uo/zIQkIJqVg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:jpQ9QMdh9TFkeAkD33OjBvo3s2MMNxW5RF5P1dllJjGxtAMaXw==,iv:E/DxC1Rhjj5vX1YOffX8w+zJvyOsbqYtb9JMS5efbm4=,tag:nGLIt0hZIqpYpRgBPdvo4Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:p6Oy4+JQMHJW39q5+RTU,iv:V/lsfoWP2WpDugtGSvSV7/ltXsSJqiiwc5m5q7vs8+o=,tag:wKs4SAfaV/zf1KFa57YJ5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Yzh2RDdUdytsb2NOenc5
            d1N4cDVKWWFzSVBMaDZlMlBXZVhmR2t1L0FVCjdCNjkzQVk0TnVPVXR6QXgrQ1hz
            SjltNHVadUF0MXNOVG5LUTcvelArV0EKLS0tIG9Mc2xPMkFWMmRNREx0WUF0TGFX
            N0VFV3ZuQVhHVG1qWTdkRkVwOGZKMlUKKyD84qczcvlmukHye/Z8I17LG0wgIIiS
            2pLcUnhvvlSAR4PdcFSsXsRDVZ352wuBRiX0tSB3Oj/e946ccFBBhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-22T22:13:41Z"
    mac: ENC[AES256_GCM,data:GbD+rzOJ1/d1y+w5hYAbvQasXb6p1wa11eTIXvjJ/BF4gcbXVLqTtHqneZMKpWe6Z9Pdr++BYcuBhEEC0/5P78qcc+XbR24EdqIspLEaVSF/ficNe381+AE7MDVwTvHjnmGzSdGRbTLmf2peA5NXCmOJqsGB2S6ks6BvtPJiins=,iv:c9XiPW8VMkkrqGq5K0eefmgbiQ+oE2tmBdmuy+zUOcs=,tag:WYhR6Uc0N1iFiZUoAHmZHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
