---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: &name jellyfin
  labels:
    app.kubernetes.io/name: *name
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`media.${SECRET_DOMAIN}`)
      services:
        - name: *name
          port: 8096
          namespace: media
  tls:
    secretName: ${SECRET_DOMAIN/./-}-tls
