---
# Source: coredns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: custom-coredns
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "custom"
    helm.sh/chart: "coredns-1.16.7"
    k8s-app: "coredns"
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    app.kubernetes.io/name: coredns
  annotations:
    {}
spec:
  selector:
    app.kubernetes.io/instance: "custom"
    k8s-app: "coredns"
    app.kubernetes.io/name: coredns
  ports:
    - {"name":"udp-53", "port":53, "protocol":"UDP"}
    - {"name":"tcp-53", "port":53, "protocol":"TCP"}
  type: LoadBalancer
