---
apiVersion: v1
kind: Secret
metadata:
    name: redis-secrets
    labels:
        app.kubernetes.io/name: redis
type: Opaque
stringData:
    redis_password: ENC[AES256_GCM,data:nr6JrLf8zjZ7CfIS8HE=,iv:wh7an9f4bSNd6WaKgjB94JaK3IxbbbEV28imSjIwWao=,tag:oQx4NQtSywLAbZBW0w1jVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK1lEMlllc0ZlbmhYQmlx
            TXpwVVVsYU9HUlBhUHRWaUEzOUhPczZmSEZjCm1mbkdYbzZWS2ZEdUtSVWxWSWpo
            THFwM1Y3ZXhiRUZmNXk2TFlGNXpmTzQKLS0tIHlwd2pEdzVSTjBHbFRScy9WNVhX
            enVwNHR1dVZjYkc5WWFjaVJKZ21PdWMKl35hCyifFW60daaoLxHHBJTm91npBxvd
            3iHoD114UJMY2/lRfP+EahVocsrQHa3MI5tDBnAYMxlvh1NdBD5LFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T07:55:20Z"
    mac: ENC[AES256_GCM,data:4EkVJHoAb82RfK1sNI/rPuV0nsIBrLJFDFByTNVqzwX+xLiUugoCEKDL+AmXOyLkovaYSeFeAN8IQUkd2tLYXGYNp3Zz7pJcRcWGnDvMZbR29pkGSMTqsqxip8vhhzOJyOiuYliQjNBbLDONLDr4x91gvV16bovOaZn9pRptrwQ=,iv:5CeluL0TmJFlqeuMd12lv3miNarRJYd9SEPtRjyBXn0=,tag:dK839bG4ihv2+L3L0j1/vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
