---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: tcp
      protocol: TCP
      port: 6379
      targetPort: redis
  type: ClusterIP
