---
all:
  children:
    master:
      hosts:
        # k8s-master-1:
        #   ansible_host: 192.168.30.119
        k8s-master-2:
          ansible_host: 192.168.30.210
        k8s-master-3:
          ansible_host: 192.168.30.104
        # k8s-master-4:
        #   ansible_host: 192.168.30.134
    vm:
      hosts:
        k8s-agent-1:
          ansible_host: 192.168.30.140
        k8s-agent-2:
          ansible_host: 192.168.30.166
        k8s-agent-3:
          ansible_host: 192.168.30.249
    rpi:
      hosts:
        # k8s-rpi-1:
        #   ansible_host: 192.168.30.26
        k8s-rpi-2:
          ansible_host: 192.168.30.32
    portainer:
      hosts:
        portainer-1:
          ansible_host: 192.168.30.184

    worker:
      children:
        rpi:
        vm:

    kubernetes:
      children:
        master:
        worker:
