---
kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_host: 192.168.30.156
        k8s-2:
          ansible_host: 192.168.30.110
        k8s-3:
          ansible_host: 192.168.30.245
    worker:
      hosts:
        k8s-4:
          ansible_host: 192.168.30.196
        k8s-5:
          ansible_host: 192.168.30.182
