---
kubernetes:
  children:
    master:
      hosts:
        # k8s-master-1:
        #   ansible_host: 192.168.30.119
        k8s-master-2:
          ansible_host: 192.168.30.210
        k8s-master-3:
          ansible_host: 192.168.30.124
    worker:
      hosts:
        k8s-agent-1:
          ansible_host: 192.168.30.140
        k8s-agent-2:
          ansible_host: 192.168.30.166
        k8s-agent-3:
          ansible_host: 192.168.30.249
    rpi:
      hosts:
        k8s-rpi-1:
          ansible_host: 192.168.30.26
