---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
