---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  labels:
    app.kubernetes.io/name: esphome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ceph-block
