---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
spec:
  selector:
    matchLabels:
      app: valheim-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
        - image: "lloesche/valheim-server:latest"
          name: valheim-server
          env:
            - name: SERVER_NAME
              valueFrom:
                secretKeyRef:
                  name: valheim-secrets
                  key: SERVER_NAME
            - name: WORLD_NAME
              valueFrom:
                secretKeyRef:
                  name: valheim-secrets
                  key: WORLD_NAME
            - name: SERVER_PASS
              valueFrom:
                secretKeyRef:
                  name: valheim-secrets
                  key: SERVER_PASS
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: valheim-secrets
                  key: DISCORD_WEBHOOK
            - name: TZ
              value: 'Europe/Berlin'
            - name: SERVER_PORT
              value: "2456"
            - name: VALHEIM_LOG_FILTER_CONTAINS_Spawned
              value: "Got character ZDOID from"
            - name: ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned
              value: '{ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l connected."; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'
            - name: DISCORD_MESSAGE
              value: "Starting Valheim Server"
            - name: PRE_BOOTSTRAP_HOOK
              value: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
            - name: STATUS_HTTP
              value: 'true'
          ports:
            - containerPort: 2456
              name: gameport
            - containerPort: 2457
              name: queryport
          volumeMounts:
            - mountPath: /config
              name: gamefiles
            - mountPath: /opt/valheim
              name: serverfiles
            - mountPath: /backups
              name: valheim-backups


          resources:
            {}
      volumes:
        - name: gamefiles
          persistentVolumeClaim:
            claimName: valheim-server-world-data
        - name: serverfiles
          persistentVolumeClaim:
            claimName: valheim-server-base-data
        - name: valheim-backups
          persistentVolumeClaim:
            claimName: valheim-backups
