---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-gateway-config
  namespace: networking
  labels:
    app.kubernetes.io/name: k8s-gateway
data:
  Corefile: |
    .:1053 {
      errors
      forward . 45.90.28.182 45.90.30.182
      log
      health {
        lameduck 5s
      }
      ready
      k8s_gateway ${SECRET_DOMAIN} {
        apex  k8s-gateway.network
        resources Ingress Service
        ttl 300
        fallthrough
      }
      prometheus 0.0.0.0:9153
      loop
      reload
      loadbalance
    }
