apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app k8s-gateway
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: quay.io/oriedge/k8s_gateway
      tag: v0.3.4
    args: ["-conf", "/etc/coredns/Corefile"]
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_K8S_GATEWAY_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            port: 9153
          dns:
            enabled: true
            port: 53
            targetPort: 1053
            protocol: UDP
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
    probes:
      readiness:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
      liveness:
        custom: true
        spec:
          httpGet:
            path: /health
            port: 8080
      startup:
        enabled: false
    serviceAccount:
      create: true
      name: k8s-gateway
    persistence:
      config:
        enabled: true
        type: configMap
        name: k8s-gateway-config
        subPath: Corefile
        mountPath: /etc/coredns/Corefile
        readOnly: true
