kind: Secret
ansible_user: ENC[AES256_GCM,data:IMeo95pf,iv:TpCZ4WParYRMfB3Kd7cfECJhz93ga+FdOQ4NEvzTSmI=,tag:ffMwx2Esu36doYnMrq0rEg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9p8v4S998UuoeTi47Rg=,iv:/YGqi6CBwqqtDNz1fty3A8vJ3AHTGoz8T1ZPWVK7I78=,tag:Iz0fzreJOiihzaUXNgcsow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSHZwdDNnSE1keXhBakNP
            cUFQUnhWNWx4M3M4dnBFRWp5VFJmV1lwWEM4CkVZbFNOQmlsZ3pwZ0tISjRvL3ZM
            OGtLVXozN0VxWkFhSXloSUFKdnFINGsKLS0tIHNGTlZSdnczdlB2OU93Y1JOaTFn
            S1VjTjAvQWMyMXAxUTMrSzBta3NPcEkK+qbl8HV+Zwmx54adDtsG8u1EAE0STfbE
            Q/SW0K8KqzCn2/gZD08I4rV5YU7TiKxqryY3Gtbw2isaK5DM87AzNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T20:53:57Z"
    mac: ENC[AES256_GCM,data:sleauinsVFP1j/R7GAa7rd0Dj7pB72sCbmE8eVhC/ZlSUBX7YgTxC6wYNJ17ck32fTU9QHiTzkVVDEb9QEAhfym5X348mXrVDPkIX3S1G8YxKS9uULtBn0QEYpW8nt0KL27oa4sS2A3x2MUjuuAgZAihKO510ev8yp0Di4mLrYM=,iv:x7wdwt/sUccStkc2HrR/yJoYsNDazx9oRBaPpo5uc4k=,tag:wyiG5NgXDsPJsAykGqz1Dg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
