kind: Secret
ansible_user: ENC[AES256_GCM,data:sA8jRAjr,iv:KTcp17FZ+d+o2T9Us6pa0+S1lkzUqlWXmbk0da+VDMg=,tag:a62Wky0S/DfQZJVhqsprRQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xi0rJOVZBWQl93zNBMc=,iv:jswWzqe0e1DxNa0Ns1J1g00FsCrZJu+4OHLK9NMyVh8=,tag:tFjIFjR74LE6V/ErpQH8sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaTFYdzFoTStZc0IxbjU0
            ZVNuWFNGd2w2Z2paRDFMR2pZeS9CMlE2N0dVCmdZOGh2emNhalg1c09pNmIrRlZK
            RjhmM3NScXF2ZlRvKzlKbGtlZlBYZ0UKLS0tIDJBQ09EYlBXZTB2NmVrZ2VDaVd0
            eSttZ0xHUmcwMlNJUGY0RHRseVA5TG8KT7C8390Guje5cWsb7cPpMH5CldUHe+KQ
            ui6FwlohcjG593YYYZLW3dZdPPVkBRzZgANEWkc4gLrvZzJ3ijGzPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-05T12:54:47Z"
    mac: ENC[AES256_GCM,data:eA6RSiD+UiHIhROOqC3dYBlgNdeU3mDjOCaaBNBr9MwjxIh33ZxPb2dc/zCs7GKxbTDK8NpoT1uAazWXsr/75vuGAEFIz9fn5lj8+uRB98uscCH9HOfsqm5k8BtFumVW5NVJsbecsX+UFuAfl+WuZUwuRtRszqlTV6+s1k/V1wo=,iv:yrTziJtJc0LF+axbie479FHax5UZJeNC7HJ3MBRT81k=,tag:R2eWHCH54Yh6j/S6Vt483g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
