kind: Secret
ansible_user: ENC[AES256_GCM,data:0FyCjkoy,iv:sFq6Vwe/rq0JFDpAYoMuczDFpexYpVyWPvlTJb4O4L0=,tag:b61Qz2Jr7zALJsRVUxoyDw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ft1A1hPwo+HkcHpvo1A=,iv:sKxf9Zuv+v/5S9s29xQJ0Z5vTGuA4o3FQd3Fh6z2eB4=,tag:z0KLkP3qgWs6+o1MGoxSJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYUtqankzTEh1VFd3SHoz
            Tm9TNjJTS01FZU41THRkbmhNNFBWUWduQkFZCms0YWJVQ2pXS3pNZnFBTVVoRDNR
            bnJORUc2QWlhMjJYN2x6RXJwSGRPREEKLS0tIDV3THY5WFBtMkxNN0VWbHN4cGp4
            aVl2eDZiNFJQUkxNUVVEUmxhb0FYZkkKIjPiiIROeZU6SvdVb5VeIeRUtViLr4/M
            3piYjbJIhCdXUoxYHoBTsFpC6KwQ9NumWSBXdcGstNeKfuZ3GcwBOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T08:21:58Z"
    mac: ENC[AES256_GCM,data:2mGMUORTC/TnO3DGO7X4RNS2iUtLfEwAjpgKpSt3at1uWVSw5pcVmSrZjy0o9qcJMUOkbi2kHLNbkrC7a5gsBqzDlr3Z7bkR/2kc5oSscltLEIo1Qw0mp+o8Unox0lDOr/q6FQq567CktDajqDfTwBcBwoB73snwGXJSE3qOfR0=,iv:GbuYSpDBR4YmGR7R34pwHqvM0Cc+tUKnnr4aL6obCLU=,tag:db+OQQhH9LMGeyinmFebsQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
