kind: Secret
ansible_user: ENC[AES256_GCM,data:56mYol4x,iv:Sy0FFheVNsQfHSdUYWVb/Y74H/e23WAA5Gl8dCVP71E=,tag:qndbyFN+9gZsvQJKp7qyIw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8Cg/akfUPdO2FrfGiws=,iv:yLS6Pu9aYrQKfR2Ktu2AGXTSWFoTmdqGHPol1+Bcybo=,tag:/RilXBuxdMIk8QEIBh6Jnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WTlUeFF0OThOYmVhV3hX
            Vm16SmZ5MnYySjZVeXEwL25MY2RvWHRoZDNZClVCcVZyWHVGTU9CaWU1MEw5akRX
            V1RzNXNzTDdQclIxQTR1dU1iTUZhTG8KLS0tIE9UMmd5clZJQnBxVUViNlNmT3FG
            TkFYT0Y4V2dpOTN3NFZmdGxqWkZNMlEKacyiOvvoP10QTKUQDTtBky5Ya2ZNtyNb
            pe92e5jdVRuZ5d/IHspsf0lsL6vFhi4EOUSxzy0P26fH8HMsQe9dpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T20:53:57Z"
    mac: ENC[AES256_GCM,data:RqE2YsL7EA+cgEDr5PGFQ3jc1+orYauTig6x4lwurmJ84QMVsRRVt2pJcxYlt0M6hgFcGKgAMMg+U8RfwEJsW0kdR6cHGKos8N/9P3MzUmvbI92wDiBr3GINNGrgttiz9bne/XiG1A4k/LcKYCoRQxwYphYhtnWd6dNVx5W7Qwc=,iv:Y4QeDUu79cWXauhlPe/bo9/xk09jYJDURc35bLGCq+w=,tag:4ZGTHo4ueApS08+UfYht1Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
