kind: Secret
ansible_user: ENC[AES256_GCM,data:lJDBitxQ,iv:oynZQUYL92fIgDGmsy2c7U9AqbhzUyhaliuHSLIZMOs=,tag:WA45xuGlNbd/CdQhq0Clag==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:YPtCGXZYg36Gp4toVkU=,iv:e26qDmAc1MbXoqs77AIHApXcF1cvFuA3p/ebniYeiSw=,tag:DL5zlLwsYdCaivXn9+C+Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ2s5UmJnVW9JdDRLT1Fi
            bkRMMWpkdzVFU3ZISmxYVHhSVmppWWVXWWhNCkh3STZhYXEzd3JGNFdRaTJac0tH
            cnRVNU1CaGVLandiQ1lSYndMbGRxWmMKLS0tIG55NEg0d1MyR2ZhdnM0QmNHUGw5
            UnhJUHhDQVd2REpsamhib1FRdGROclkK72bJKnWL64EJQpXbQFqWomdZ0MzZGc5l
            GGqbDSGAO8WrxQqHF1qlR00bpUUGaFqBOcATISXlioLTsrhzZKDfUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-22T22:13:41Z"
    mac: ENC[AES256_GCM,data:0EV/1xwMG29fo1eg+edEh10KULIocMfq1w1gly6L5Pb3SEvHB7mCRG44ErRek7GEpIb1b6wHeOAcWJ4s68T6xefnkofq8oWLyZkq0kQFJawz8XzAOrRMo6eZGG/xNrY7iWEyWNLWoiETnJOBMkJO4soKn8S/T6BYwP0pQD4PTiA=,iv:Nd+CT6NeAWWrk4cEoG/M1+1kwH43Ko0xSjumjs8strQ=,tag:qIISaFa42k9sVkw+qhW1kg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
