kind: Secret
ansible_user: ENC[AES256_GCM,data:hUeYIAT1,iv:LMPyPPyaC8umEx0cN2l+uv12FUqiWtSDVhOVmJi9YI0=,tag:pnxEl4ZHQMKZfmU+89BPlg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4XTQn7PIedhWogc3OVM=,iv:VtADwe/wcDweyWv8sUw2S5whzfTjZMh9p9VbwGLzvCI=,tag:oABnRL65Y34e5yMCh987Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMLzJGOGNLZE9rYk1Xemww
            VHJRMkhtc2huNEdORXBHd1JzMTUxN2pKTVhRCjRLSkNURHEvSVZxYVZTVXB5ZXZk
            WnEyQjlGT3VJbmI5NjRQanpyaVo3VlkKLS0tIEFIOWwxTHowdG5mR1hMblpCS0Qr
            N3ZaMjEzVVVUejRDek1sUzBPbnFJY28Kam1ha6/DLL0Addd/6nHb5JtkyZPKKjPr
            s7CS6FmZfhjerBeZN9fWWdqz57E8kSbhhwkevQpQRbcxbimwwqnwTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T19:06:22Z"
    mac: ENC[AES256_GCM,data:UiF/dX7yXe1Gg0r0X01GSicY9Isr7zkr+wHVYd+i5v3WG0odauStS3AuVDF8g+t/i7rcQfGKhFbv3lcjakXpazH3DOW8IIIw0GTYwt+Et2+dujRr1e8L506cXwRY8iz7dTp6am3wOqWpJnTZdMOH/8F8i9nCwzj5kCOa/MloPw8=,iv:fTpwX1TpkWQIxuQGt079aax1FslgJvMcx3pEdcD+PqE=,tag:jWJtfIkIU5JzmzgG3gvOBg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
