kind: Secret
ansible_user: ENC[AES256_GCM,data:9L0vS2Oq,iv:F+ixQaGm60w/kgiwfTLa3yiqHpIdzAIljY9ZwCEkAw4=,tag:XLoQJPGsr2oNKgPhilbZLA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U9LLGn/ORJCNHL7G1NI=,iv:pmbiAIqhk2YVU0o2BIv2hxQhR4IzgLH7QITWDziYytQ=,tag:YVuaTa3t+JO5QSYwfolcGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYODZNSkllUDZkaEM2bmlH
            azdJM0hHSWVzOUdXMEhXbFZpQVVGay94bEVJCmpGdDB5REh6MTh2Qkhsb3dPNWxM
            MkRhb050OVpmdjU4QzJTbW9BNGFiU00KLS0tIDIvdTBpc2k2cTh0ZmlydFltb0RX
            K2RkWWVjSFpUNWlUSmxwRk1DM1ZQUmsKCzQ3IZVXCUZBCgWiKpSktVFWB6gbVmSz
            S5YHU8ef1ZCNtnqzBz9iHBoxgK2JsrD/OLKS3NP1J3tHLTb0M8JV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T12:01:59Z"
    mac: ENC[AES256_GCM,data:sfnChiYmmqbtpep45WxJQvbQ8ey3wS0ooH8hCCgsSl0wTdxJINcEP5Dkt3fop+YWfBOHvSCK3VEEATFMBSOUeRnM8QukKAdX6EgufbpSUj/e0e+ykdpiUq+j+ByTBN2B4Ywww9uZ17bwpYc39WS+qX4rOtd+x0xAeKKOyW3GEeI=,iv:PTgWIJRmK4o76UOdbqIVZBPZ9TLo6wqFQXMqCNTTtXI=,tag:ux3WMgfrMB4o5IC9tdGcow==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
