kind: Secret
ansible_user: ENC[AES256_GCM,data:PWO4jjzJ,iv:u86iH5tVkghqrmIQtec/Exz6F1bKf5uHzNhxjCNDUpY=,tag:FsSLanGr0UrJ1pUlqz6FGQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mBxiaDHimcevmmkFA5o=,iv:8nDmUB+BMmskK2iJ4yNLA4CdeM/tJjqXcIIeC+6TIro=,tag:mxhg3EQciuPbGMCQWPi6+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRnNlV1FGM0E3OEN3Q3Zp
            d21PZUcvSmJ0dzZIMW9MV2NYOWRVNkVWWEZzCjdmSXhNK0V2TVk1Y2tGQ0tVWS9q
            SDhTc1Nxa1dSTzFMVlJIUnU3cUNsQmsKLS0tIDFJenk2cjEvdm0xTXNUV0MvN3Yy
            NnFTMWozNzhadFZBVngycXdQTHEzUUEKU6xNyKebSKICxxb7H8usmNiIsIUnfRZn
            FVXCq5NvieefgnY+X1PFMQZwlrs+jBwoYTNjgGgMf7u85mkeULMYFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T19:06:22Z"
    mac: ENC[AES256_GCM,data:A4qbrPYOugh3XkMwO6BXIsU/8fPodAOV1SshLeV2zKG8Bx3J6zGkCDtrjZoflOB0X9aLg5amzFOJZLZq7QZXKpdHj0WlDPAt5zOH4/SRLqpt6R84Ri5dwsXPW/jC5gjrfyqeXRghueVau2dSstxw9V8A9RcqIxyAXX1WiRJY6tI=,iv:nt/qvvfDhW4WNIAJYZw5ObUKbSES+WCYuZIT+suWPLQ=,tag:wvuc3UhcMRWJ2YEDzyMN4g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
