kind: Secret
ansible_user: ENC[AES256_GCM,data:IMFdO+qP,iv:fxtXdRJyRmJvdTuY/uF2rp5S7s0nnwjSOasL0d7qPpk=,tag:c3yW51IQNHwjpIeTjJMqLA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ZaG3Yxw5yuBSShm17hQ=,iv:ebTCrv5Y9tBG8pOxcdk38MiyhwWp1gpQplg97J/Qi3w=,tag:agl/hTV0sQjee57N3PrcoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cmZOUUtISUMydHA4ZlVP
            Yml5UkRsd2dHb3B0MGVQa2ZLbHJNTlRvaENJCno0WmVuYjB6TjRGbThZck95ZTNq
            NS81MXFDaUtRSjcyYUdNbG9Ic2wrbzgKLS0tIHlrdlJSKzlxbzhqRVpEUTdyemlZ
            OE1XUmlnZDZMdC92cXNhTmNiYUhqV1EK0D78PYnQaTRY8ZA94hCFv6U/ovfOZdt3
            +TbgHRb5kU/k0bfkqVthLaZBSzxbN1roZLE4DNjhN/hDWkZH1NiUxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-05T12:54:47Z"
    mac: ENC[AES256_GCM,data:KrYDmdvKqYG9pJ4kZprGWmEQ6cyzuq25FDqQYqqqq8WmBxdiLcwTF/O6IfAhwk6e9BbHAQYlbWzr4e/NF5bi3bDZWMps0Au8CiYXkmi2oSJbS9xjoM5HpIINTFg0j7PYJgPlvdNH8OYH5sma0rvdGDzXxPVuKcSQ8cSWU7ILA5I=,iv:p2K/EIt9aaQjwTDQbytkJIHcaagCbWi6zxfhSsWe+28=,tag:q4GDPw1n5coF/hAmYByzkg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
