apiVersion: v1
kind: Secret
metadata:
    name: prowlarr
    labels:
        app.kubernetes.io/name: prowlarr
type: Opaque
stringData: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweUdiK1NWclllSkRqT3Ev
            M2lEejEyRWNkZXk2T1ByT2VMeWxSZUZiSWtzClBnVHRxVWJwR0tsSUhITlUraWRI
            QkdTMlRTd1ExTXpzRU9kR3B4TVNjZzAKLS0tIEsxY1BzNllSSlFDVGJMOTJ1ZHVG
            cDR0VXRJcFRtTmhBanJDVGZqaE9ydU0K0YiTOBN1UZQdemCT3uPtxIOr4u8P7x0I
            KUgOseGdgma+7vvqb6Fi8+56yWe4392E9P5bsTBGk1mMEBvBa2qmMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-04T18:41:56Z"
    mac: ENC[AES256_GCM,data:1Dg4llfXmCaRpi0/4YvPPWn+LokHO923GNCkXFTMhsjVdi7SHsfCgFEC8agTepN8vYMmhslUl9D4Qk+1RfYTSCwanmTW8gpx0ltAHmzcGzDbrC/jzzBP3r+InEzpyPk6MEPjYVu0IPE4+EuX7T8jjmmdXmH6t9aCCZtolt5CSZ0=,iv:I5CSxcw3s7TtKM5t746qJUK5GC93RZm5+V28JvI6gc0=,tag:dHq6FgrLgGU52rtJzOw8Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
