---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.2.4.6635@sha256:0848d89de846b7cc977cef28b7c1d950a773e6c4d6867dca26e615c6bf32e063
    service:
      main:
        ports:
          http:
            port: 7878
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enable: true
        ingressClassName: traefik
        hosts:
          - host: movie.${SECRET_DOMAIN}
            paths:
              - path: "/"
                pathType: prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      data:
        enable: true
        type: nfs
        server: ${CONFIG_NFS_SERVER_ADDRESS}
        path: ${MEDIA_NFS_SERVER_PATH}
        mountPath: /data
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        cpu: 300m
        memory: 500Mi
