apiVersion: v1
kind: Secret
metadata:
    name: radarr
    labels:
        app.kubernetes.io/name: radarr
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:ynMCNRvc7NaZEACt9rgdwoj21ZupS8+H955eitODqQA=,iv:1ZrYoaq6AWCGiRF2qiTTKFzHKKEERQuLylerrAmRnHI=,tag:afUhP4Y0WmPAB3ogSTi3tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseWpXdGRTTkpJSVYvK1ll
            dkFzYXFieEdyL05pbnNIN1Z1L2QwQmpjaFFVCmZhWG1Cc0s3bGFINDlyUE5EZmNy
            UXl4TGt1QXo2KzhISkxuTVE1d0dGVnMKLS0tIHdMN0VWKy8vOGROM09RbmNmYUpG
            S2xzREJPS3V2VmtpYlY3aHQ4UTdMLzQKoBk8BwPMjKU9Z2+jC7KOC4ivbJlHtdPr
            g0RGpv1/BpB0b0YgM+ozHngPEeX3S6HMvwKwvxVw1Z83CF2sogXPbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-04T20:58:07Z"
    mac: ENC[AES256_GCM,data:dZHKuOveEu17UYWQPUp2lGVx2xVAM9Xa09I8kUgOFctzxoPtWxIPoP9dJ6wRwKizaeh8hCnd4MbYnelru/cBdlNy4rN/xVkPEA/YSJnxVlBFxLDE77cJn0biaZBOK665oYQLdSYvhNhX16UtzNgjsBYhga4fEyDBnBBRa2+cimQ=,iv:dPfsXaaumiTC4cN5TMyGPW/+VmO53bxGKgzW9YWlEXk=,tag:4nJUtGWrAnH+DMq0dTFW2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
