# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BOnolbG4SXAPgg==,iv:drOjzE/eyK0WP0aHopQDUXjbwCCmPQm0IkRTTAWmf5I=,tag:+R5xHHfvkxAmmbgq9BH3xg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8HEuiDCOsl3mw9zAZdv0SBWGbc05MWm4,iv:Z3KUtDNfs9xbDj8+67fdEYiD0Q9ldu9rt60+cQOtfCw=,tag:T/EDnGfLjoW+J2Dj67LaRw==,type:str]
    SECRET_DUO_INTEGRATION_KEY: ENC[AES256_GCM,data:TWdm6+4h5UgM4sX/o5qZQdPIEHk=,iv:q7q9a/oaoO6qsRTIiye1Cj/aWkf5DrbJexURzSkhzu0=,tag:s7res9g1ipRyvc9PdHcOBg==,type:str]
    SECRET_DUO_API_HOSTNAME: ENC[AES256_GCM,data:vsS7TGLHlzZIJk5QWum36yvECIKb3vyrFGoVCg==,iv:1N4jkjijyp2AbnLd7rs0064k9EQtPTsjCxFDIGSoPB0=,tag:/KGkhczvxGNI36RisTa3UA==,type:str]
    SECRET_AUTHELIA_ENC_KEY: ENC[AES256_GCM,data:eVC4OBwFt8qVSBYt4QRFjKn1Wlt1cjq2PgI=,iv:NOkLYnk99rLUZI06DLUxGvKB53KHKYjtqL54vRW9/mE=,tag:79llUyVHbNML/Hl6Ja3Oog==,type:str]
    SECRET_AUTHELIA_PASSWORD_0: ENC[AES256_GCM,data:KCBFegjBZ4a2U6oKdOhRvEgel6KL7joO/R4JtBM71yYiEorCsr912sYRdKVkrESZRUwcMSsV1dzxhBh66dgbwxaRRC9X4Af2cg/hrRUjS7GJLhBjoAzaMEaGhfbbqbE5BQ==,iv:IVm8c37qEY6BmcMWWyq2VVUME4ytl2n7W1QjaQQGFMA=,tag:REJN3vfzYhP9DBUeM6MlWA==,type:str]
    SECRET_AUTHELIA_EMAIL_0: ENC[AES256_GCM,data:z58swifCXR3uIHj+f+qUj9Dr6yDI,iv:pRf6stYSkShxSXBQV++8wPExx0027JQMf6W7pIS+9S4=,tag:BkTLom3wbzYB+tsMccL7KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYUN3Ulc2ODFYQVRUeHNm
            VkI3a1g5ZzlhcDN0ek5DWW55TDlvR1dZOUd3CkRpc3FYNlZVVVJNR3UweEpqV3FB
            S1grc3Y2am1nRER3SUVXL29vQkRIYjgKLS0tIDZjUHFKdUlXM0h1a2EyQjR2My8x
            T1lBbUZTT0ZyMnl6VHpVSzFGSkNTcEkKnRgJ9MKZh0kiUAwAswgBg7hH8ngI/7cM
            DylFIGhKtJVvRyK+8Xh55X/sj00YB/uQMwYX2qeXviq8bjdY+Tc15w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T18:42:13Z"
    mac: ENC[AES256_GCM,data:cPZbItxR4zH5eO5i9lmQFWno0xjaSq1a+vgTUwzLR3gEanS2x7zuW+zlFFgNqUQs+6F8QBWJJuVgfXVCJh1W8Y1LTXhgglZH0M+3ECY+5eg9+6rMDQGSwmNuWEvmaG8neQXG6b5IhDhWlFiOuuAIdlt/LIf3G+sChyAXVm4tnl0=,iv:Ys4BSvX3E3W48YwQR/3MI4X29vLBhm6JOneFNmBx2Fs=,tag:s+e90m4ZY8v+moZPRyAS4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
