# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:S3yMD6TH1ThVwA==,iv:j44UDARsp7wMyT8B9go76py3WG8tccZ/r7jKSxjj0hU=,tag:Brak+pEjZIzg6NFhVjqYMg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6gRqUsifwBavkLQQhiDPEkYWuWi6hIL/,iv:F7I4ITkiNP48FE0PJ+aOIIyypxpll8ctbCJ326oRpa8=,tag:8BjIhSKxTgl7eHasRpnCzQ==,type:str]
    SECRET_AUTHELIA_ENC_KEY: ENC[AES256_GCM,data:bdw4g9tZWvEoD5h63diFu0mphymlJtj49gE=,iv:6UzfQYV7NmbOYp7ueePPqZ8bquubQqXn53zU9MLGyZ8=,tag:61BRRs3xGAkiT4afekvzxw==,type:str]
    SECRET_AUTHELIA_PASSWORD_0: ENC[AES256_GCM,data:JKdjm+F7Icx72tsr/fm3mGM0kc46GcVhehhoqNXef0LQPiYYi2NoTqGUvtsWHbD6wAZ9LT4aldd9BXrqjC/Av9QNKMb5I0/gyt04tHGarItNMHk4CaKb69CwunaWt2Yksw==,iv:S6enXT1m/g/7k/VIMLbdKOFhPA05VUY3yTWLmMyotoE=,tag:2UAALetMkwdsJN4/l0CA+A==,type:str]
    SECRET_AUTHELIA_EMAIL_0: ENC[AES256_GCM,data:Fl6DsfUiBGfr9NbQXx4GyIVGgNfx,iv:exRwA4S/j9zgLCTxAuIsCEENNIBBx6zLlEdZfLfb8wY=,tag:QmDUbMSI2NvQn5mW3FyeVQ==,type:str]
    SECRET_DUO_API_HOSTNAME: ENC[AES256_GCM,data:DmhnpuXjS2dxbPdu9oIxNG8uSsq4HkhABjLUbA==,iv:HOClkBZEtTViCfnD7jR74cKYo2/oS8s29U9VLgBIPuM=,tag:Vv6s/lOrPljbcajItnRTiw==,type:str]
    SECRET_DUO_INTEGRATION_KEY: ENC[AES256_GCM,data:JZwGB1whvl4iwFyvX5QxAnamW+Q=,iv:ZkYaQqGBalVLXyky4QfWz0e1zP603zcv879QuSx2y00=,tag:+sNhKs8YO01McGHFUID4cA==,type:str]
    FRONT_CAMERA_RTSP_MAIN: ENC[AES256_GCM,data:xlZaGKQ0/zlbfXOiu+xE2Ph18bxYF9sS7axfx2ZwDGY7GDwp/bZEMpEcIjHPih3d27uA2sWeOKo5JA==,iv:aCvf1mFCRzLylmAX9jEQv/UQjDrTFDG39ULmdlEFHsI=,tag:7epwrHQ56H08EfjVSXcPPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SGh6d1FEQ2hsazY2V0p1
            Qi8yM1h3TktOR0RQNitZK3hUb1NvMThuWWhnClIvSnVQaWpoSG5lMGc3NmJxeEs2
            dW5QZDd5a0ZHUWNveE11ZXRTL3FDVFkKLS0tIHI0bFhTVWtVamxjR1dtcUhHOWlt
            WTR0Tjk3Q1pybkRhb29UQjNhbXZVeHMKfM9CWMDTiFiPiiIhu2iLch6JC4dw/y3G
            EbDgxtKBV/8hV9bqNEM7jePPeSVkjMdg1iF0UBGxOw3KOvaeFI7m1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-24T21:39:50Z"
    mac: ENC[AES256_GCM,data:9Os7UTXDD3mf+FcVkEIpdwzOMikv3H/RoTjyLvl4w1XWpIc6uOCLXGmHHWbVf+lgVHxWJoCq0VPYSDLSP58cl6k/CyKb/WSsgIBZkfcUfAQZtPKY76IqoXr8obAvLETuS57B/3AkeSsFNBaFbSz7v9mYGnzRT80+DDMcl7hmNB4=,iv:McNZbBcW0tlsToZg+NAdWit6mHG5IGb8llpcP+iPgn8=,tag:lz0AdbM0mXPbNnK5D9cs8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
