# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:P/N8RGHs1TPOYw==,iv:4czwGjg/IQqOedmRh04yiDPZ+AaBqLDvQmSwtquSOlk=,tag:0lGb9cK0UI4WatvdnGT/3A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qAZCaNRsha4vBSYkpO+k9Xw0HvvoiP4G,iv:w0pBpQEhwOQfjjF9hjbRR78Gwrta3DYgene1pf2ELF8=,tag:LjBvJUR4uuIFNIGb1yGRLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaXVCVjJwV3lQUmQvd2Np
            dTIrN1ZkVzZXVWgvYS9GZEIzc0ppR1MwNGpFCkN1eDhtYlg1R3c0dERGVnpCamhO
            OC9zYVcxUGNtTE9nUHh6d0h1N1pMczAKLS0tIGZLMmNyTi9NNzFsU1AxTUU4dkZ5
            NTg1VGNQVHd1T3BHSnVLcEFvbVlTaU0K3y+vpsHBY1GfXGiZeW2IJrsENC6vYlO2
            qJec7V79V43RKWxTPhcoZrBlwkSjeDHa3S7nn1y+GiLl+OV8PPOzFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T19:06:22Z"
    mac: ENC[AES256_GCM,data:RUoV6MHL29CSyiqhfEXFCHkowPMaHv7kjwak6mZm+INu3kJx39S557PiVikm4MKrGVCcjWOLXgxlQ6aNq7PEjoJe5DmLJiW6dPaH3ralqbObBWLpmkjl6YZ9Ip4i8efsaAl6XkuVVFbfeGAnHpBlAjt8/1rbpzYPThIXCuBnsEE=,iv:mroQ4ZCSlrscRkscGiCljI3PRVAtwVPrlh7UoF8uQ54=,tag:qlPBfiTxuvSSHj31qUad6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
