---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.30.50-192.168.30.70
  METALLB_TRAEFIK_ADDR: 192.168.30.51
  CONFIG_TIMEZONE: Europe/Berlin
