# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BOnolbG4SXAPgg==,iv:drOjzE/eyK0WP0aHopQDUXjbwCCmPQm0IkRTTAWmf5I=,tag:+R5xHHfvkxAmmbgq9BH3xg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8HEuiDCOsl3mw9zAZdv0SBWGbc05MWm4,iv:Z3KUtDNfs9xbDj8+67fdEYiD0Q9ldu9rt60+cQOtfCw=,tag:T/EDnGfLjoW+J2Dj67LaRw==,type:str]
    SECRET_DUO_INTEGRATION_KEY: ENC[AES256_GCM,data:TWdm6+4h5UgM4sX/o5qZQdPIEHk=,iv:q7q9a/oaoO6qsRTIiye1Cj/aWkf5DrbJexURzSkhzu0=,tag:s7res9g1ipRyvc9PdHcOBg==,type:str]
    SECRET_DUO_API_HOSTNAME: ENC[AES256_GCM,data:vsS7TGLHlzZIJk5QWum36yvECIKb3vyrFGoVCg==,iv:1N4jkjijyp2AbnLd7rs0064k9EQtPTsjCxFDIGSoPB0=,tag:/KGkhczvxGNI36RisTa3UA==,type:str]
    SECRET_AUTHELIA_ENC_KEY: ENC[AES256_GCM,data:MQENcpIiX5Vd+KbLg4s=,iv:Jo5vwl/3L1P0N/N4ONocl/zq5zmqlbBG6AOq10RIVOU=,tag:fKtDwl7FCJz6PHFIzvnc0Q==,type:str]
    SECRET_AUTHELIA_PASSWORD_0: ENC[AES256_GCM,data:FfP47FTek65JGx9bHlUuyg==,iv:vVPcmv9XByGchBHFgLgNrw3IhQK8M7mJ4okP7st5888=,tag:7AX3n5rhi4tPfjQKku2TXQ==,type:str]
    SECRET_AUTHELIA_EMAIL_0: ENC[AES256_GCM,data:z58swifCXR3uIHj+f+qUj9Dr6yDI,iv:pRf6stYSkShxSXBQV++8wPExx0027JQMf6W7pIS+9S4=,tag:BkTLom3wbzYB+tsMccL7KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYUN3Ulc2ODFYQVRUeHNm
            VkI3a1g5ZzlhcDN0ek5DWW55TDlvR1dZOUd3CkRpc3FYNlZVVVJNR3UweEpqV3FB
            S1grc3Y2am1nRER3SUVXL29vQkRIYjgKLS0tIDZjUHFKdUlXM0h1a2EyQjR2My8x
            T1lBbUZTT0ZyMnl6VHpVSzFGSkNTcEkKnRgJ9MKZh0kiUAwAswgBg7hH8ngI/7cM
            DylFIGhKtJVvRyK+8Xh55X/sj00YB/uQMwYX2qeXviq8bjdY+Tc15w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T07:39:09Z"
    mac: ENC[AES256_GCM,data:htUHK4x1dqv9Vh5dJItMTsTeq6Ap/dxsrmZ5TBrq3rn4d4XmIV4ZFAR0LQ4g2dvcxqrTrQtvHlKm/KqaiADiRjcSoaJgNbsPfe9tg+JSEufcY+LHBRRrrpsVMcQWEWGH1oJklqXwwGGSTpzoR9H4+R38basZnjE7C/+LzpwTiF0=,iv:GRQyfuDrdb8H/UMBW+m2Ksw05P6Q6p4Ry51GsdelHzo=,tag:+CX9b38Y4aHKVEIPlES8qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
