# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BOnolbG4SXAPgg==,iv:drOjzE/eyK0WP0aHopQDUXjbwCCmPQm0IkRTTAWmf5I=,tag:+R5xHHfvkxAmmbgq9BH3xg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8HEuiDCOsl3mw9zAZdv0SBWGbc05MWm4,iv:Z3KUtDNfs9xbDj8+67fdEYiD0Q9ldu9rt60+cQOtfCw=,tag:T/EDnGfLjoW+J2Dj67LaRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYUN3Ulc2ODFYQVRUeHNm
            VkI3a1g5ZzlhcDN0ek5DWW55TDlvR1dZOUd3CkRpc3FYNlZVVVJNR3UweEpqV3FB
            S1grc3Y2am1nRER3SUVXL29vQkRIYjgKLS0tIDZjUHFKdUlXM0h1a2EyQjR2My8x
            T1lBbUZTT0ZyMnl6VHpVSzFGSkNTcEkKnRgJ9MKZh0kiUAwAswgBg7hH8ngI/7cM
            DylFIGhKtJVvRyK+8Xh55X/sj00YB/uQMwYX2qeXviq8bjdY+Tc15w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T20:53:57Z"
    mac: ENC[AES256_GCM,data:4AMC/lWqQVkrhQmiYLD99g2jy2YhZD3wyXKo8kYsmKY6WEUpgued0T6td8HcwcoQd7dJC/eMgDGd3p6NJbr7OZKVnSybustRi1LKRF9/D0tY7MLpDHXj3ilfYHypV369cwv9f9IB0a34f2fB053tXMOQBpLddMRjh4tkiSPAabU=,iv:TjwP4+QnmIM4sajoZ5/ssEhuppDJ0rwBCYSFPohieks=,tag:rXxm8iZR8ywNZQbjhw/okg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
