# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9JNCTtgRNgRz2w==,iv:hd/LHnhMB3vpOwc7fEqFtTNNAoe98INlX58ufeWlA4A=,tag:voMMI6LiFoDkwJ5MWoMyYA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9R/KPAuqWQpFBVo1i6hsZN1JoEk1uc0x,iv:NLWablRCE/4RvzaKD04dhV7a3O7qwfXOUheogUgy1yI=,tag:hmjzk4BMX5ZC8/iyfPkN0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcUQ2YXVUSnZaZjYwWG9a
            bXljOElCUGVLN2ZnTWJnZ0xxeTAxNVlnSlFFCk95ZGd4SkR6YU9TbTV5aC8vdWJk
            ZW9pRGFXc2RqUWJwMDA4SFlZU3RmYUEKLS0tIHBNVVc2aXVleEFxdUM2SEZpUmpi
            WG8yUGJtRUlGek1NSmFvVXpCQ1BTNHMKCVQB13C/oyvhc1mX42fMtkwVxb2QitsE
            0HuctDcDsy61Qz+gHDF32oTqVbfea9R7Bi9DzSNy7XU8UTG73FAfJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T12:01:59Z"
    mac: ENC[AES256_GCM,data:9V0zfi2vz23RbNep58oMVPVIMn7LK+daFIUZCLNmwWbr4sMOF3fZuokmWE9seCOzuozxYP2f6UfBxQPM2+hHhU/mAdBGe50SLxOMKP6v6L8Icxj+7M9nisvZU7Yz2rS4v+gaK1jIYCpO8iXPPOfD0mp8Ceg4Ayo3sYyXY9GcubY=,iv:jr+uUI84b6xvFR8cGx1vkI0yE71YM3WTuL1BTVlvMvc=,tag:OZY8VGN/zTV1cKhASL+Zqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
