---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: hyperion-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /home/hyperion
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  volumeMode: Filesystem
