---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.3.2.6857
    service:
      main:
        ports:
          http:
            port: 7878
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      data:
        enabled: true
        type: nfs
        server: "${CONFIG_NFS_SERVER_ADDRESS}"
        path: "${MEDIA_NFS_SERVER_PATH}"
        mountPath: /data
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        cpu: 300m
        memory: 500Mi
