---
piVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: &name radarr
  labels:
    app.kubernetes.io/name: *name
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`movie.${SECRET_DOMAIN}`)
      middlewares:
        - name: secure-headers
        - name: authelia
          namespace: default
      services:
        - name: *name
          port: 7878
          namespace: default
  tls:
    secretName: ${SECRET_DOMAIN}-tls
