# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: valheim-secrets
stringData:
    SERVER_NAME: ENC[AES256_GCM,data:mMWm8EniN2b4Ra2KlA==,iv:YPkoV4IdC5Ghn5tC6FqA9LN8JqgcXyAQeUII/S4ye1o=,tag:3a8or+28Tq+wR4DDPsFTjw==,type:str]
    WORLD_NAME: ENC[AES256_GCM,data:kS8UdV1P,iv:M1u+FnvEt8mue2irp4e4AtdCr9+jjdy0RHUXAVarMmA=,tag:ws4Yd40zl6HEQg5yfrBn7g==,type:str]
    SERVER_PASS: ENC[AES256_GCM,data:kxUx76kBfdCzkA==,iv:jPZyv5gPinsmhxFhb1g3sG50RywPZ0vqfhdQC2ZIzAc=,tag:ph0yZ6v957txX2+d2WWcOA==,type:str]
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:x3Xzq5h7LpEx8j+iK0o8vBNs3Dfn4Bb5Upfz0JF73lTFrXmrX3J0trf03PURYkzOId6SDQMfx07iy9aI6EYcfhEIGY9538wj8Bwn4ra3TO3s8Ml+uspOQmmHCKTNC3mQXNQUiQoZseh+STqp6baEBmLiToYdMg4sfw==,iv:iHu/Xa408fxeqckDzJrzm+ucrvDaXPgDXATTC4ZbX4M=,tag:FPsX1m4PxxS+sGhcGwdC3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSFk4MmR2eHJxL3Z0akk3
            Y3NSTkZiZXhRZGhVcG05SCtBY3NCN1NRNm1BCmFFMTFkVTBHWHNFQ3hnRW8yVUtD
            ZzFwalNpWWRNclc4ZVBZdmxxQmpTM2MKLS0tIDByWHpRUWtELzZobEZoWElmelY4
            ZEF1SS9JcnM4T2lSc0FGWkZqNHhIa1EKlU7hDYnZio2XQbmjr+4dahiwWjN5LAiz
            uFMJ/Cr/oCgtMNL22NuZruvjhHfdIS8VTYjdzRJkyehPe2zoNk+Lcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T13:41:01Z"
    mac: ENC[AES256_GCM,data:QkzbRr7Hc+hOgfSbH6atw6iLxUNz280xFHWf+k9MSUo1IYaZ8T4DgxmNKI42zBVek8ivGsYE78VdU30nfBJJoXjexIuvchcp8dnSE598Q53XB91bMwe5mSyehQ4njF/hOQNfkPoXWdcK5H4C4LuJjnEb7KT9AH9TpFqnTnZPFWM=,iv:osZhYPXP7r0z/8mfgFkMDA7ZKXrEyWHPQCFnaodaAOk=,tag:7tjE4MyJsl1UeHe6IJJ1Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
