---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi-poller
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/golift/unifi-poller
      tag: 2.1.3
    env:
      - name: "TZ"
        value: "${TIMEZONE}"
      - name: "UP_UNIFI_DEFAULT_ROLE"
        value: "homelab-controller"
      - name: "UP_UNIFI_DEFAULT_URL"
        value: "https://unifi.${SECRET_LOCAL_DOMAIN}"
      - name: "UP_UNIFI_DEFAULT_VERIFY_SSL"
        value: false
      - name: UP_UNIFI_DEFAULT_USER
        valueFrom:
          secretKeyRef:
            name: unifipoller-secrets
            key: user
      - name: UP_UNIFI_DEFAULT_PASS
        valueFrom:
          secretKeyRef:
            name: unifipoller-secrets
            key: password
      - name: "UP_UNIFI_DEFAULT_SAVE_SITES"
        value: true
      - name: "UP_UNIFI_DEFAULT_SAVE_DPI"
        value: false
      - name: "UP_INFLUXDB_DISABLE"
        value: true
      - name: "UP_PROMETHEUS_DISABLE"
        value: false
      - name: "UP_PROMETHEUS_NAMESPACE"
        value: "unifipoller"
    metrics:
      enabled: true
      serviceMonitor:
        interval: 2m
        scrapeTimeout: 30s
      prometheusRule:
        enabled: false
