apiVersion: v1
kind: Secret
metadata:
    name: unifipoller-secrets
    namespace: monitoring
stringData:
    user: ENC[AES256_GCM,data:UdtCoStHDc6fdhI=,iv:19v2mLm8mUb+v9bBi2xoQyrC+n/cSxc3wQIRGASMy38=,tag:dq2VW3OPJieaKzHlGwubBQ==,type:str]
    password: ENC[AES256_GCM,data:DitRtLKTvH3ZZAfRqOLBtlzZ,iv:sqj+w0cW4EBKcPFYkj6YRYCqVMm16FqxiC1QgyEJ/Ks=,tag:kPUs9ScSqV6+8kaRT2mpdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcWIwb0o1elhZSlJWOEYz
            Ny9lSlhrWi83TzJLYWg4dGpGQ3Nydkp4YnlNCmZRVUJ6TlJTNUdua3hWRjYwTDZK
            VFk3R0UydmQwa1ZGS0xzcDNDeGRha1EKLS0tIGR3Rzc3TTVOVmJpd0RlZFBJRjhy
            LzE3Z0NKM2JMTnB5cUFuYUt3NXMzWXMKqewk7Bq8IrNj9sxP7+t4bh4AI1XBW5iY
            m+h2ZC0sOwvRai65b4oj1YJmiIiXwN4MJ/sVldTzL8tY8QtjFAq2UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T21:06:51Z"
    mac: ENC[AES256_GCM,data:rjXZlzLc8mvaUUwz6V+b0XlbqZ784ZUDf/KR5fuci1EANUAiDLnMGL89cCmnjszVOQgrvSGWxkcu5taMqpTxU2BI1jw3IbJeZEiPsvQWsugWFjk1sI9mtDJcik78uReZtmULLrN/8hM6p5Qe6FplgMkS3p3zLZeSl67d6AqdUlo=,iv:k2ZMJt43bB92s0RAQAWfknaU7C3HIkOoh1txcHBB//8=,tag:smJBUcBYGBjMRgc3vG+mwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
