---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceAccount
  - clusterRole
  - crd
  - configMap
  - podSecurityPolicy
  - role
  - daemonSet
  - service
  - deployment
