# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:7Fr3RrZaXm+reisHiQuaikcxWWOO4IjR0BYBE2WHTJd9pnUD/YLLCOdeaQ/bjWy5XbCFsntGId60lPHwzc8vA6crNmMpJWBkoxmRhAxLyRlb+9HFMeqflKesvrNs/33RZ7ycRdustg8FhciMgUt3drJIw7tKVeVO,iv:oVtbjzBlllufGgoTMeivjCzrqjy5vfKXZ3VaWqPifgA=,tag:XNnoiD9nUZEfvkbubPzxSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUElrVlQ1MjVBb2ZKYmll
            aEdHZGUzNFcwemthQTBTdkMzSUlHa0xHbVg0Cm9OeVgyaVJCT2Y2aklCcEducWdI
            ZzVKdDNXaGFsZXo2akpkbS9sNGQwbzAKLS0tIGE4aXlMMDU2K3EyLzZZZlJzVjV5
            b2ZHK0tJaWY2YkY2aWlpL2Fwd3FBaTAKAOyZsZ+RbC9CO/GxXcVzNE4FLV5XpQLf
            GUcv9sJuftBiVMhJCq67ZtxcfRpH/+GRbg/EhLbMrHlpyEpNxxi4ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-28T21:19:38Z"
    mac: ENC[AES256_GCM,data:i7FGkEH7ospE71gCu0gikLXraW58jN8bzy9QefDP64lE/YM+557b8HjpU6aCv7zH4fV5oQkGkWWR/3IpLzUeajWkKNcoI7xde6voBeqg/L30B5Un0XwoNr18BbzKUyD4Q7SJ3sooemhZL7NIQC893QbInTD+49JlpPRf555YLss=,iv:dU8J+EeVyFNr3BNeeEnab6uhA6hsXzvK8y1BhecVgRk=,tag:HWbz3d3XYQ5zRcybvBM+3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
