---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    eula:
      accept: true
      company: clempat
      email: clempat@users.noreply.github.com
    global:
      persistence:
        storageClass: ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s
    ingress:
      create: true
      class: nginx
      host: &host "k10.${SECRET_DOMAIN}"
      urlPath: k10
      hosts:
        - *host
      tls:
        enabled: true
        secretName: "${SECRET_DOMAIN/./-}-tls"
    grafana:
      enabled: false
