---
apiVersion: v1
kind: Service
metadata:
  name: hyperion
  labels:
    app.kubernetes.io/name: hyperion
    hajimari.io/enable: "true"
    hajimari.io/icon: "television"
spec:
  selector:
    app.kubernetes.io/name: hyperion
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: http
  type: ClusterIP
