---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn
    - name: smtp-relay
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: docker.io/n8nio/n8n
      tag: 0.217.1
    env:
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_PORT: &port 80
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_HOST: smtp-relay.default.svc.cluster.local
      N8N_SMTP_PORT: 2525
      N8N_SMTP_SENDER: "n8n@${SECRET_EMAIL_DOMAIN}"
      N8N_METRICS: "true"
    envFrom:
      - secretRef:
          name: n8n-secret
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/icon: "workflow"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "n8n.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
    volumeClaimTemplates:
      - name: config
        mountPath: /home/node/.n8n
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi
