---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  labels:
    app.kubernetes.io/name: radarr
    snapshot.home.cluster/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
