apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home-system
    labels:
        app.kubernetes.io/name: authelia
type: Opaque
stringData:
    frigate_rtsp_password: ENC[AES256_GCM,data:GOCzsrJT58T2nQ==,iv:Bnv3RG3R7kw0s12OrrcwxwxRwD/ZOQFJO8e39TRf8Uk=,tag:0kojOsQxw4MqUjyEEZ1xTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVE5WVGtjTnBPTlIveTRK
            TlhHRUcwWFQ2OUJmditYU2xMOStBNjBsT1RrClpXYXROa2VSL1pldVM3VUpVQVNs
            TnNLa1lZeUdZS0Q1T1o5anMrSnhvSHMKLS0tIDU1am1UN2x1cTBYaWRBSWNFbW5H
            cVpwOGtJa2t1QlQ5VjltMUkyYXMzN0EKOr26g9WuWaCifpU1Fm+xvfIy+pS/lTDK
            Vsot3e5VJ0xgLze8WfE9PatqOh7bbQP/OGcU4Vwanvlwyg5Xnerj7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-20T10:22:32Z"
    mac: ENC[AES256_GCM,data:LbLfz7yB2zOuHi1kxkbobTFq4zKxepolmEorZQNVXtL2Da4ZCZ89LxuZwXnbLqFOgl9rSRWOzuC6+WBktoN1DEYNYqIuEFDf4xU2GAxkYJKn4tPRbeXo5eJnRk3vHyAamUVb0fmnr7kMBxAQiiZZX0qrwWIcqQFTnUrQR5JpSuY=,iv:j+WeBUTgO2q9Xp9C/NGeKbFQSyiZWUzy6l8/CM0UDNw=,tag:d+flE3GQpPq2mYvPkEFZyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
