---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - longhorn
  - default
  # - rook-ceph
  - authentication-system
  - notification
  - cert-manager
  - kube-system
  - metallb-system
  # - monitoring
  - nfs-system
