---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-config
  labels:
    name: traefik-config
  namespace: networking
data:
  dynamic.yaml: |
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /certs/tls.crt
            keyFile: /certs/tls.key
