---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pgo-cluster
spec:
  metadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  postgresVersion: 14
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: on
        pg_hba:
          - local all all peer
          - host all all 10.42.0.0/16 md5
          - host all all 192.168.30.0/24 md5
          - hostssl all all all md5
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
    - name: instance2
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi

  users:
    - name: homeassistant
      databases:
        - homeassistant
    - name: authelia
      databases:
        - authelia
    - name: recipes
      databases:
        - recipes
      options: "NOSUPERUSER"
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.1-0
  # userInterface:
  #   pgAdmin:
  #     image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-2
  #     dataVolumeClaimSpec:
  #       accessModes:
  #         - "ReadWriteOnce"
  #       resources:
  #         requests:
  #           storage: 1Gi
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            incremental: 0 1 * * *
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 8Gi
              storageClassName: nfs-provisioner
