---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-redis
    - name: cluster-apps-smtp-relay
  path: ./kubernetes/apps/default/authelia/app
  prune: true

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: authelia
      namespace: default

  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
