---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`longhorn.${SECRET_DOMAIN}`)
      middlewares:
        - name: headers@file
        - name: authelia
          namespace: default
      services:
        - name: longhorn-frontend
          port: 80
          namespace: longhorn-system
  tls:
    secretName: longhorn-tls
