---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  routes:
    - kind: Rule
      match: Host(`longhorn.${SECRET_DOMAIN}`)
      # middlewares:
      #   - name: authelia
      #     namespace: authentication-system
      services:
        - kind: Service
          name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-tls
