apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authentication-system
    labels:
        app.kubernetes.io/name: authelia
type: Opaque
stringData:
    authelia_jwt_secret: ENC[AES256_GCM,data:xV6Lg/b1M5+aNBvXhv7FSeSiemU=,iv:OsHSmy3EdDLw1ttyUbQE2ayylRwK0GXi66KZqhVsKG0=,tag:LxV+Mh10Yj5k5L2AkFourg==,type:str]
    authelia_duo_api_secret_key: ENC[AES256_GCM,data:HkAiZrM921RvmmH8S+We1AtZprkmurXa1Zxbzw9v5jVfc+AeWQrg5WWaBpeKXQpTTdZqrP9Rmuc=,iv:rJtVsBYTExCedDLtkk2hrGILj06eN4igcZ+WTbx9XdI=,tag:RIKwkJiktnQBRLdcH7BnnA==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:xcdJ7N74EcO5hrwDk+aoBj35yWs=,iv:Veu6sBTrXgn7U18wQ9rNjWh4QQK5PqVbMQ54LArR52Y=,tag:K/bcZIjdF6yY0iovucSGXQ==,type:str]
    authelia_notifier_smtp_password: ENC[AES256_GCM,data:rHj4eUN11fZOtzavZbo+Zg==,iv:lP4KwUnN5/gY6rAHUeI0bKBRVkjBzsjR/eOwPHmfCCg=,tag:I7wHQi/s9VxRc3pF0J7ejg==,type:str]
    authelia_session_redis_password: ENC[AES256_GCM,data:aCBcTRupxPaLEXHWrmU=,iv:iZNKUbQzlhJ/xxppEWIxcVoQCDvW7RKETAFvDQBnLrM=,tag:Mk+9gGtGVFgXyb/L8yrJFg==,type:str]
    authelia_storage_postgres_host: ENC[AES256_GCM,data:DtHmhNj0g9zxvopCbzE=,iv:nPHRWCzx+E1V8l9EPdEO82b24pHNGiYCHjDj2Qzto9E=,tag:uZDVKxFeWb1ARIKZrYambg==,type:str]
    authelia_storage_postgres_port: ENC[AES256_GCM,data:i195nw==,iv:IHfoF0lnNcnJkYQKaT0RuEOVhqUfPU4iXGWoh3tqzlM=,tag:3N/51hZ80G+qIJenkvxXiw==,type:str]
    authelia_storage_postgres_dbname: ENC[AES256_GCM,data:SFzjDU9temk=,iv:UoFrHYcT9Fqn5ofxGOENL/d1NzHNcbQ7qjaKOrJWXg8=,tag:DXkN+9wUvY8TV6gZ/iMn2g==,type:str]
    authelia_storage_postgres_user: ENC[AES256_GCM,data:/M2oSTDEHnM=,iv:JU1uc9pHTJJdcOety7OGkBBY6cM4cKmZk0Qw+YMBwvQ=,tag:b7qD5ITEr3arx/21mM8gig==,type:str]
    authelia_storage_postgres_password: ENC[AES256_GCM,data:GkNkvE7QoueGqYf/4WsXCz67hWw=,iv:SGS9VoGUrchM8IiqNrMVoemgvIJex1vbrRt14aEGBZk=,tag:msJM8/W7vSOcmb0HltQQgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ1YydEJMT0tySk9CakIz
            bmN2Ri9BdXNTVFRrQW9leHZ1cjJweVdlUFVVCnFrTFBxYzRZQUpNVXMxeW5TUjc2
            ZGVHWHVORWNBRjJncFEzZkVZRUxXc1EKLS0tIGc1RXpQMnNwcUtuYTVDbC84K0lr
            QlZMNEQ5Z3BsUjU3YThBN3NwWjRmNmcKhizAiOsSg31A1y3cgNb/fhM+2kb7u+V8
            VP7p2MFJoOkPVDfk1hUpoCkGSgycMjbRAMwHdcipVEXKzAOHBqpWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-01T12:50:00Z"
    mac: ENC[AES256_GCM,data:9ZQKs3XIGXimCyrfFAbZJuFsE3KmhY0EmIFS3A095aHy6SmoUheh+JJLLh+059YkzI8OvpcI1QosZYie1TUlbQdC9yUuwyYZW/Sv68ozRER7FCajw/q2pKFWF29AmPZPccvFHeWYds0/3GfwhReaM+jMKyD9LG/AxU8LsXaL5ug=,iv:PjfXGk5Bh31llWaphUKGX3XGTfNF1Ro+eoOfhcreuFo=,tag:3/7nPG+nQ3Rr8VUbBt4k0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
