# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:rP2CTAN5p2u9XwVkzyeA57wlljPjnKnWupjb2AIXVDwYTQjqJQ==,iv:RjS2KcdQwr+/euiVKae2IxZxUJyt6v5jM3qd/w5lXm4=,tag:REjOUHFI5GV6PuOU7f2sMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWVp5QXljZUZBN3AxcXln
            NmVxcUVpSy9oenA1Yk95cjdmK0NiZ09VR3dzClJ4VWlYbmJZVHhNYXc1NUNzM0x0
            YWIvb3FWdWh3MjZZZkhGWlI1bmJMWTQKLS0tIGxxcUNNYS9WTUlQODZ0NHFoSkw3
            aTFXWjFUdXVYUjJnTUNUNlYvY1BsMXcK7HtQuYziTQKe4GRgc6NFNC2GQvaoYNd2
            q5prA2llBLEdoZ3K3OjCLQi0dtUF9sPBjkUCAm3uBU6vVlVMU5E7vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-04T21:17:48Z"
    mac: ENC[AES256_GCM,data:GtoyBBKFYNOpyjpHH6Zp/R2qv2xvY9wdWAdrEYDGaRLrkMJUav1xNNi45207vn6orSFHDr2pDnpNqEWWbg4Z77pxm6tVLfO4vaHxVu2zS1C9yb3c32AQVITR3ErnrR/Ketvba3KvnfC3ZjdkZwT0m5QK+KxekRLOTVFIkioR1vQ=,iv:W/pX2/R3v4GWgnZqIGeXw1cxOyXrULLCtI2NDIzAK9A=,tag:fvvU23yEBPoSV+BqCh3swQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
