# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:JkwKjsPRcF8paOmJdh/8JWGJJMpuYL3C3LAcVTH1dr+KL6DqAw==,iv:eVIaewDZ4MWymX9K+mqdpDwAjNLMSBqyjmKmcWAHpqo=,tag:xnuk2Z/slXjF2rWRDTr4Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUDFWL3hDSGJMWFJXQk9p
            dndEdnV0MmRqaWJBR1NXVllCR1hrdlhkdUVJCnIzSlR2NU5NL0V5ajlGZlVQY08z
            VTA3N1BzdWVLdDVObCs1SnZGUkRvZWMKLS0tIDJiS2cwSkxOTEtteGlVSzhnQlVH
            SFJkQmFRRlZYajhJYmltTHIyd2gvOVUKiei5kqHuo+ycHDLl8nn+if2QcmvyTL9b
            bJCWAilCeg4efY21KwKxRxm6n4Ur49UONuI71U3uGz4OFZQak6tD+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T10:21:47Z"
    mac: ENC[AES256_GCM,data:d6rNJFPHz6TyE1cYgtpDKO1oHzuGOJt8iRakOV4k/mXYwdUiG1F5NP/1KDl0GHG5aVFvQfL49QBT9PxsJsNW7Ax6dmTOQRJtmMFeoE7BJgU9BCwq77UsD/Ssc6LKleFNZpEgc59lkWxkj8zYT2Gw3rQjGnUu19xcl5EXhIvjTmM=,iv:lHlLqyYwVb/wZcy2dxo5OQ3TJJD6tVbt+i19SBFIDfA=,tag:+NvOQNJhIiDpPMzhlvpI4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
