# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:PEZ8YMY83RFz0pWtBiOdIlx/ydfZnCWqCQQVD/vnqTtXP1uwdA==,iv:HKx84D2c9D812YXirR4JhKmL/KLE14Vvjbl2Gg+5z2E=,tag:XNsx+7ImsEkzMJbTTX+JSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOCsyU1Z0eVhZenFJcWhi
            Mks1eitycVpzanNSMnMxaTFtTXdOT3ZBbkNZCjYwWTEyQndvbXozaFV4QWxpZlZS
            RmRTejlMdnZZUjlRcjYyMklhVXFLR2MKLS0tIFV1UzVSekxLcS83NHBMQ2t1dFR5
            a3lLdERKMTJORTVJM0I1R1NFZTBGaGcK85prm5bX68poD7P2ZfJZoW1+5lV9+Szx
            Vp0bPh8I9P/1REXqPRq1Nn5HnLIOFsebrDuzTquocdOzApYsRRNtEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T12:01:59Z"
    mac: ENC[AES256_GCM,data:zT4tjHOkT2bvWutdnBmkoDoka+aU0/aL55t33acLIaWoAmPXLQD8rOqMTdYk7hy3uFZl1DiWNITLwMUqadb+wok3EuT43BpB6gCHymgNgZ5gd7W6BzJCQhRnWYpiKT4xN4xsHCXZfFLXePixfuNdhIDQixznUfF/2bNREWPEjd0=,iv:cUg9yFUwo+lhdAayg8XiE7Iiist3rGWHUbOLzt+xoGU=,tag:uEBzDEwP2jaeFc5AnrgZyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
