# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:QgQfrTPVmylObpxMVfVBHNwgmkSvcNCwhC92YktuXVlNcF8soQ==,iv:bx7XWtexzshTR/FDySSQsY+/GYhN/6Gctkjm7VbtFqA=,tag:8ljwwtp9lPfUTKLG+L08VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvLzEwZnhHVUU5a3VBTkdp
            anhhOVJaVWN6L2F5VUtGRDVUYXlyYWV6dEU0CnZxQnNLQzBDRm4zelp1dlUxQldU
            c0ZkK3IzMUl6eWE2WGJvMU94R3E1cm8KLS0tIGg0ODF0ZUdKQjcvWTFHT29nZko1
            aW5IRy9wVWRHZXZLZ2k0ODV0bFd2SXcK1IJeKePkAW7sJUcyuBqrZSvHTO3dQb4a
            tn1YeuFPJYillkA2yCyLovUvCPErXake5GDJ5BeaN0XDZ4BaYOdidQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-22T22:13:41Z"
    mac: ENC[AES256_GCM,data:qHZHr8gdKSw6eOw4bHerS2iO/U8l54+enGqZaoujmY7vora7qZWwSRsFYv6UU8uTcwc9j46BsndUL3zvdev37o1ZTnhVWQiyPkcuVeKJ47PGWjGq+mUdSP9Zh3HD98O++XAw6hrzvseHe5CPyYjEEmaCXcoR9YUHzUY75OafCG8=,iv:Mr5Nbw/gKiYZuec1wo1y8mgkvRvWyJnptcI9D4vDsgE=,tag:ay/ovx6jhmVrt3W1C9WFlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
