# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8a9VfAD7PLWXMImgdvFYinIEV96l4sKiYWmGEas9gfLqO9FDiA==,iv:Vr4ZyojK2VsKDDTujr1D4CSPvHAjKaET6g3AGnGXWDA=,tag:8mUQwm/++KY/WWssPRTxpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCR1J5YUoxemJ6d2IrSGtl
            VFVDSUU5WWFQaVlOWU1QWlUybVZsa0FybTNNCitwQXBhQ1dNSzRoWGt6SDMyR2pE
            QVIyRXM4a2x0QVAzMGorVWhhbVpndWcKLS0tIGEyNG9CY05YRTBDZExhWVZRUE5K
            eGZpSi9KVTNWZk51WGg2bE4zbDZ0cWMKZxBgybVRWtPrjk+Ql0Olw0WiQjdd3Qh1
            R3gus91iu7o3Ya4ckaNQisCFZLQ6upZtEa8WFz+eLTLf03fsvw9Vjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-05T12:54:47Z"
    mac: ENC[AES256_GCM,data:+XIgp2ykrdET61OhcHM31WFTJjwepJSC/2384GKFV8KiyNC3YaIxU/tR1+A7fLuOyRpAV3aPBhkq+4Ei0HvTokIwFeN1d0lugruDJb8klHJvOpExMVZICipxE6VvA8ipSIVxB5NybSoN6g9ZXkGs9pNuLRqVtkYdHI56h9ScEGU=,iv:2L+voRIPACb9E9J7UenhdBp5eLR7Z/6pqn1uNnyjfMs=,tag:KhJ5fByCq/C0HKL/3rn9TA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
