# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:TsDq85mTz3MAunNORtz+z1X2KoqST0Xmxo1dXbbqYYdnOLsJpQ==,iv:1KLtdRYxsOF6z7B3d2AJh8+7FPV2ZxCalI91k8i/cDU=,tag:QmVuCVsf+8OdHGlBs8zucg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra1RvQXNlZ1IyeStIbGNW
            M0N1YXdCV2FZcjdOMy9ieU1pQ1dxb3RyeENrCkVFQzdzOVY1ZERUWmdiNjVJY1NU
            ZkpyU09XWDFMSlU2N2xSL29tT25zUTgKLS0tIFEzTkVrWThjR2tJT3ZhUW1uYVlG
            b0JoVDdwbnZNUlF4Z3JJN0hHVTlUUlEK3aAA54tZlWX0J4WutWCl2sLpbdsIwjAM
            5NC6+6sb7sq+79CInEe+l+tEPv1Xh5IzG88SA9IB2F0ZQAUi92YTGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T20:53:57Z"
    mac: ENC[AES256_GCM,data:UTP9dInWNSj6vbH6l6N3yeyT358PTPS9WE2GByYFT6DgqxZU53/649FAavFu8Y+5y1PPQSjT+eUAeZUdFwEnUJj6Q7acPP9cDED7N9FmuL5Nsz2vqu55g2DXQtfB9qELHKllPCL+Ler1KtSmtNcfpxzForkVNMHZcsumWioBKUI=,iv:+LGDQqml8gtronONaYlNyvUBrdxTWA2b3gTRtLKXocY=,tag:c7W2MXqoW2mPMTk4U5Bu3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
