# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:sUQNwdTcrD5AiDw7LEnbZo7tdTooB8GeLT9QwBeTUQAAuoWwvA==,iv:OWK6h4n/BPDokp3W4u5hK4nUdHnUQWlylD/f0eGl0Bw=,tag:TNXAA4TllrJwbqaigEIU1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUkpVUUFwVHI2OXgxK0Zh
            aUFHeG51ZGQxa2ZhMXc1M3BuS3NLTmJudGdBCmd3Lzl0bDBML3pKVTZHbll3Wi9X
            b3QvZzlKYUpQTVdiUkRxM2VUeXM1QkUKLS0tIFRYRjFJaGVpSjFnVkt5Q1Z3Nytj
            cVNmWG55RkRJbzByYTFEK1I4Ujl6SWMKsuvFLXEcqcOgavw1833Ac7ROC4tzX1xf
            EKqdthKMbdU9tmvADKxify/j1LvbKRT6FCC3zLr4Pbk7l8O+oKLKKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-22T12:04:02Z"
    mac: ENC[AES256_GCM,data:2MqpbFDH7hdF5R5WB+YXVAYgKwPobQ5u2F4b+wiePVx7m1lYdf9O9rNp8QTTPr5U8TMOsj5LWF0yUbAmFzR1bYG/2mt9OT4SqCtIoe0CS13DwP8YAGOagdgyapouw5QVvnKSNqT63+r0zrd0vwF8MJ783b/DhuR88FuiJymx/nY=,iv:SyVVNUhIWob0qse/++HOgkIR9qGVI8FM8nNsqgb8uEA=,tag:3CdfFkW+yAeda9WBubUi5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
