# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:EmbhFbHBycRsylgMEED/jYinwd2wWnWtQSDwCi/uGdQs3rmt0A==,iv:4vNGua6jICmpEzSDlFy/hRVYLdLAwupQATKEc+Xzo3U=,tag:RAVp1Q4BGvXh4vNlNfsPTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ0RXV25Fd0k5eUVieEww
            RU5YOHFBNXFFYzc5a1lpRFpaNkRnOUFheHowClR4ZStjbnFJeG5zbWJtYklpbVJ6
            VHp1ODNTSytoYWl1VUgzQXRiNVdydGcKLS0tIG1Pc0FRNzU5eVVBdi8rS0k4NlNQ
            b2l1N3JTS0J5RDhIV09oa2ZqejltQnMKPxXxuhvj2FCkg7LaYKBaT7W40bJJjQdV
            nIww2B89bGTFEU6c4puAIz0zo5IPOy8oDigodMLOvtwyXy0Yl95RKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T19:06:22Z"
    mac: ENC[AES256_GCM,data:mDK3RHDMzemgCSkCmj/s+YEXs+9mTNfdYYJWLqybL12m4QPv5yDCr4YDEnrDgD9kI24k14Leh7UEMQ7tF6Anf3izLMhicjf0rLR6NZ0NXJZ38SoDoQ/WQvO1IFj74Qg8td+IzmzZWATxqIIcJUwgXGctacDRzbhhCMXAA+UG71M=,iv:WrHVwPdDzv8dH3odjFWfUHsUuL1kXaI1gCUB8/j3lak=,tag:GQ5nALnzVdqG/NIIilyrKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
