# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:c/K43HIBVQH1tqBO787x8Ha6/E+FsfaMJL4zx/P6T4jEwNuQeQ==,iv:B50iDf7QLQMTjwWp4GkLtQ7gYUIl8eAq6aoCRzGcwzs=,tag:OSZ/bD/yXoIdYWJGSTFYwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja2FHTXM2eTkzZnpvQytM
            OVk4ZmZFQ2JPZ0hCZmI2YVVIcUs5WTJVUkZ3CjFWKytLQXp4anZpTko1ZTdhSXNL
            elRtSG1EeFpEOGd5YytFOHpEeGJaZEEKLS0tIEkrSG1YeWVzODA0UDluZW80eGZn
            RlZkY1h2aHVxSkd3akYvMCs4M3JUWWsKJxRlJs+rdchfsVxR9UWp4V3QsGQpEi31
            kp5rBoRUmCbQZMvmIrdhEcLWYYsLmPKXsXD7fGE18m/RnEdL9Ar3/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-03T08:21:58Z"
    mac: ENC[AES256_GCM,data:IkZ4R28FTS/oiBNZon+W5I3qp6B6hyW1CbsOCJdi6tt3tgycc7b8I44f1vgjA7NYjfeyTVsAKj9T/hF5xRWkAFLcHPvf972OweTEY381CVPTd3CSM/94BYSPhMQQcNxZ7eq4oyW7ESDsRDLKhgfpf7zdC08+NlF8IvM5yqgRB9Q=,iv:Y4F5//PbndZVy8BuWIJFwAmkYj2OnSj/7Hdk7+YBQGY=,tag:1UovBhxgHtJa7CATSWfd2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
