# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:RhXTvfmyMnY87mysRWiiFdT+cFB4hBwZZ5IBWEbNPIridSYbbw==,iv:PrnlfKkaHKOrs2snctcs4nMlfebHjY+42bdo4np1Qk8=,tag:AuL18qMISFByIBfE3KLRMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTUlHOFlLUnhYeUdrb3NI
            eUNHRnBRSkZzcENFUlkrd1VYRDE4L0EwNlVvCnA5M1Y4VjJIT2VpZDZQbUd5b2xq
            RW5FZTdEaFY1cVNRb1paQjBOOWo4cnMKLS0tIHlQdSszaDR1TUFOWkRWajdJQjFw
            MVFSNFdkaU1rZzRkTHBkVmQxUnpEbmMKSLJHE/MTFg6q7sRxOFH/an/B0uL6SHtS
            cPVtP9VBGvCUJqqdbNLDuDTffinDajU3e90gyizVAgF6eCrzihuWhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-07T22:42:50Z"
    mac: ENC[AES256_GCM,data:cBV0X7lkQLGwP7Uk3uHZU1FCcVeCtKPWqCUqve1ZBM9SZkWS6m6xNSoXIP78qSfB10H4O+0Ha24weYv0t879ujJP0kvTJa/piCMTH+NYbv4l52KWlVSPE6V/bc8ZhALLZDbXHBO2nZenScofh1J7OsGvO2oaanoqw6DQ9UbvvNE=,iv:yonLhd44Ht4KbAikZ0HvvL74n1E4fWE+045+p210H/k=,tag:QB70J/pv4iPER1lI7fYJYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
