---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  labels:
    app.kubernetes.io/name: recipes
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: recipes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: recipes
    spec:
      containers:
        - name: recipes
          image: vabene1111/recipes:1.3.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: recipes-static-files
              mountPath: /opt/recipes/staticfiles
            - name: recipes-media-files
              mountPath: /opt/recipes/mediafiles
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          envFrom:
            - secretRef:
                name: recipes-secrets
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-recipes
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-recipes
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-recipes
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgo-cluster-pguser-recipes
                  key: password
            - name: POSTGRES_DB
              value: recipes
      dnsPolicy: ClusterFirst
      hostNetwork: true
      volumes:
        - name: recipes-static-files
          persistentVolumeClaim:
            claimName: recipes-static-files
        - name: recipes-media-files
          persistentVolumeClaim:
            claimName: recipes-media-files
