---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - metallb-system.yaml
  - networking.yaml
  - storage.yaml
  - dns-system.yaml
  - authentication-system.yaml
  - home-system.yaml
  - system-upgrade.yaml
  - monitoring.yaml
