apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:DDOBXJY=,iv:AHTW8Ng/4jvMsll5ekeLR1phPLD25VD0RIhsrLdapDA=,tag:i91zwOBzvKzSI+QtpaylfA==,type:str]
    admin-password: ENC[AES256_GCM,data:YZqkgKwJlKPuaQ==,iv:q4qmzSm3AzlEMCZ2qCaArcUg/aY393NYMX+8o90QweY=,tag:VlyIs4CuCp29FHGhTWExuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMFVWYWhIa0lCWWRDZmFa
            UFo5UjFsbnZjYXZCYzRic1dnOElhZFdqZTI0CkJZNlZjWjdRZldNNmRMRlM0K21y
            bGhQVlFnVmRNNlhXWVZiUHByWllOOVUKLS0tIFlEbjdMbzhuZHU2UU5KdVBQWGhD
            ZDB3STBmS2twbXVRSm81WG1aVkY1TVEKiXPMRBiVbx9kL0LR5NH+Mm3slGsZyaoV
            ZE5LhppRHfgwEKqrkiTLMFCd3ts7kNiTAPvvkbIsUqw7Y0+8JKOr2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T19:24:03Z"
    mac: ENC[AES256_GCM,data:zCj+TYYwhtZiDpDKpBL8w0nQOhAGHH28PWDHDCBQt6fuEM96pKngw1Lxu9/OhwBI1SnbUNSDozT2iN/l2ZLebdOoEGtSiR07vfB/7ZlyIaaQsbXUqJf8z3wubYqJlE8aDdCttxz3fXE7EAXCtlu7tF8sV+3XJroubLovRQGnQBk=,iv:9Gz1JbjbX65K2wT+2l10Pkyu7EmF1m+4RY2d2R23+k8=,tag:taLl9QZ6mjLyvYd3wLnmbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
